### ISSUE TITLE
CONSENT-polish error: "std::out_of_range"

### ISSUE THREAD

**Issue by FSciammarella** [morispi/LoRSCo#14] opened 2019-11-18 23:57 UTC
Hello, I tried using CONSENT-polish on an assembly I just made, and the reads mapped successfully, but during the polishing step, I got this output:

> [seg nov 18 19:14:22 -03 2019] Aligning the long reads to the contigs (minimap2)
[M::mm_idx_gen::15.945*1.76] collected minimizers
[M::mm_idx_gen::18.335*3.14] sorted minimizers
[M::main::18.335*3.14] loaded/built the index for 127 target sequence(s)
[M::mm_mapopt_update::20.323*2.93] mid_occ = 68
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 127
[M::mm_idx_stat::21.345*2.84] distinct minimizers: 92021864 (66.90% are singletons); average occurrences: 1.726; average spacing: 2.921
[M::worker_pipeline::50.284*7.54] mapped 29353 sequences
[M::worker_pipeline::67.976*9.78] mapped 52649 sequences
[M::worker_pipeline::80.970*10.97] mapped 116369 sequences
[M::worker_pipeline::95.152*11.70] mapped 124348 sequences
[M::worker_pipeline::110.222*12.20] mapped 130275 sequences
[M::worker_pipeline::124.943*12.63] mapped 128853 sequences
[M::worker_pipeline::139.306*12.98] mapped 127235 sequences
[M::worker_pipeline::152.574*13.37] mapped 126839 sequences
[M::worker_pipeline::166.227*13.65] mapped 127379 sequences
[M::worker_pipeline::180.047*13.83] mapped 127576 sequences
[M::worker_pipeline::192.868*14.03] mapped 125926 sequences
[M::worker_pipeline::206.344*14.18] mapped 123109 sequences
[M::worker_pipeline::219.054*14.30] mapped 124745 sequences
[M::worker_pipeline::232.380*14.37] mapped 123676 sequences
[M::worker_pipeline::249.819*14.34] mapped 146939 sequences
[M::worker_pipeline::264.535*14.44] mapped 147196 sequences
[M::worker_pipeline::279.352*14.52] mapped 145912 sequences
[M::worker_pipeline::294.141*14.60] mapped 153104 sequences
[M::worker_pipeline::309.657*14.66] mapped 140964 sequences
[M::worker_pipeline::325.499*14.74] mapped 107461 sequences
[M::worker_pipeline::341.473*14.85] mapped 36040 sequences
[M::worker_pipeline::358.330*14.95] mapped 50015 sequences
[M::worker_pipeline::372.500*15.03] mapped 140480 sequences
[M::worker_pipeline::386.612*15.08] mapped 147703 sequences
[M::worker_pipeline::404.677*15.04] mapped 138115 sequences
[M::worker_pipeline::418.094*15.12] mapped 133603 sequences
[M::worker_pipeline::432.206*15.19] mapped 132248 sequences
[M::worker_pipeline::449.498*15.30] mapped 149423 sequences
[M::worker_pipeline::462.899*15.33] mapped 147904 sequences
[M::worker_pipeline::479.873*15.42] mapped 143469 sequences
[M::worker_pipeline::491.898*15.46] mapped 140355 sequences
[M::worker_pipeline::507.337*15.49] mapped 135256 sequences
[M::worker_pipeline::526.417*15.58] mapped 130704 sequences
[M::worker_pipeline::537.434*15.59] mapped 132700 sequences
[M::worker_pipeline::553.271*15.60] mapped 125887 sequences
[M::worker_pipeline::567.989*15.64] mapped 130033 sequences
[M::worker_pipeline::582.503*15.68] mapped 124767 sequences
[M::worker_pipeline::594.313*15.70] mapped 107302 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 --dual=yes -PD --no-long-join -w5 -g1000 -m30 -n1 -t24 -I1G SRR10150407_1_assembly.fasta tmp/18Gb/SRR10150407_1_merged.fq.gz
[M::main] Real time: 594.691 sec; CPU: 9333.764 sec; Peak RSS: 7.730 GB
[seg nov 18 19:24:17 -03 2019] Sorting the overlaps
[seg nov 18 19:38:09 -03 2019] Polishing the contigs
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 55) > this->size() (which is 0)
/home/src/clazosky/miniconda3/envs/CONSENT/CONSENT/CONSENT-polish, linha 201: 27324 Abortado                (imagem do núcleo gravada) $LRSCf/bin/CONSENT-polishing -a $tmpdir/"$alignments" -s "$minSupport" -S "$maxSupport" -l "$windowSize" -k "$merSize" -c "$commonKMers" -A "$minAnchors" -f "$solid" -m "$windowOverlap" -j "$nproc" -r "$contigs" -R "$reads" -M "$maxMSA" -p "$LRSCf" >> "$out"

Any ideas on how to solve?

EDIT: The output file is empty, the sorted_exploded is present

**Comment by morispi** [comment] 2019-11-19 09:13
Hi,

Does the error appear right when the polishing job starts, or does CONSENT work for a bit, and then crashes? Just to know if it would rather be an error with your assembly or with CONSENT itself.

Can you show me what the headers of your contigs look like?

Cheers,
Pierre

**Comment by FSciammarella** [comment] 2019-11-19 14:45
Hey, @morispi,

I can`t say for sure as there is no timestamping and I was away from the screen at the time.

The headers are the ones created by libcb-sci/raven:

> `>Ctg0 RC:i:40 LN:i:15496`

**Comment by morispi** [comment] 2019-11-19 21:25
Hey,

Yeah, your headers look normal.

Just thought about another potential reason for the issue: are your contigs stored in "one sequence per line" format? If each of your contigs is stored on multiple lines, that is most probably the reason of the issue, as CONSENT requires each contig to be on a single line.

Cheers,
Pierre

**Comment by FSciammarella** [comment] 2019-11-20 19:42
Hey, @morispi,
I just checked and they are normal, a line per header then a line per sequence. very strange.

Greetings,
Felipe

**Comment by FSciammarella** [comment] 2019-11-20 19:45
Also, I still have the temporary paf files, is it possible to keep them and restart after the alignment step?

One other detail I failed to mention: The reads were downloaded from SRA, so the headers are non-conformant with either pacbio nor ONT headers
> '@SRR10150407.13.1 13 length=580'

**Comment by morispi** [comment] 2019-11-21 09:30
Hey,

If you still have the PAF failes, it'd be possible to restart after the alignement step, yes. You should run something like :

`./bin/CONSENT-polishing -a TMPDIR/Alignments.paf -s 1 -S 1000 -l 500 -k 9 -c 8 -A 2 -f 4 -m 50 -j NB_OF_THREADS -r path/to/your/contigs.fasta -R path/to/your/longreads.fasta -m 150 -p . >> result.fasta`

So, you mean your long reads start with a "@" instead of a ">"? Do you actually use FASTQ format for you long reads? If so, that is most probably the reason: CONSENT requires the long reads to be in FASTA format.

Cheers,
Pierre

**Comment by FSciammarella** [comment] 2019-11-21 18:13
Yes! I glossed over the filetype restrictions, as it only actually outupts errors on the last step.
I converted it to fasta and am running a new test.

Cheers

**Comment by FSciammarella** [comment] 2019-11-21 22:38
Things are acting very strange.

The polished version of a 465MB genome I set to polish with 18Gb of reads, set with the --out flag became a 2.5GB fasta file, with 736 lines, versus 254 original ones. When grepping for sequence headers, there is a LOT of duplication. The process is still ongoing.

Is this expected behaviour?

**Comment by morispi** [comment] 2019-11-22 08:17
This is not the expected behaviour indeed.

However, it sounds like a bug I already fixed in a more recent commit. Are you working with the latest version of CONSENT?

Also, can you run a `sort -c Alignements.paf` to check if the file is correctly sorted? Your problem sounds like an issue coming from there.

Cheers,
Pierre

**Comment by morispi** [comment] 2019-11-29 10:42
Hey,

Just tested, there was indeed an issue as you described.
Pushed an update to fix it.

Cheers,
Pierre

**Closed as completed** 2020-05-05 08:38 UTC
